// src/components/study/FlashcardsView.tsx
//
// A flip-card deck over a region's muscles. Front = the cue (muscle name);
// back = the facts to recall (origin / insertion / innervation / actions),
// generated by studyEngine.buildFlashcards() from the existing clinical data.
// The student self-grades each card ("La sabía" / "Repasar"), and the count of
// known cards is persisted via studyProgress.

import { useMemo, useState } from 'react';
import type { Muscle } from '../../types/muscle';
import { buildFlashcards, shuffle, type Flashcard } from '../../lib/studyEngine';
import { recordCards } from '../../lib/studyProgress';

interface FlashcardsViewProps {
  region: string;
  muscles: Muscle[];
  onFinished?: () => void;
}

export function FlashcardsView({ region, muscles, onFinished }: FlashcardsViewProps) {
  const [seed, setSeed] = useState(0);
  const deck = useMemo<Flashcard[]>(() => {
    return shuffle(buildFlashcards(muscles));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [muscles, seed]);

  const [index, setIndex] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const [known, setKnown] = useState(0);
  const [done, setDone] = useState(false);

  if (deck.length === 0) {
    return (
      <div className="flex h-full items-center justify-center px-6 py-10">
        <p className="max-w-sm text-center text-sm text-slate-500">
          No hay tarjetas para esta región todavía.
        </p>
      </div>
    );
  }

  const card = deck[index];
  const total = deck.length;

  function grade(wasKnown: boolean) {
    const nextKnown = known + (wasKnown ? 1 : 0);
    if (index + 1 < total) {
      setKnown(nextKnown);
      setIndex((i) => i + 1);
      setFlipped(false);
    } else {
      recordCards(region, nextKnown);
      setKnown(nextKnown);
      setDone(true);
      onFinished?.();
    }
  }

  function restart() {
    setIndex(0);
    setFlipped(false);
    setKnown(0);
    setDone(false);
    setSeed((s) => s + 1);
  }

  if (done) {
    return (
      <div className="mx-auto flex max-w-lg flex-col items-center gap-4 px-6 py-10 text-center">
        <p className="font-display text-sm font-semibold uppercase tracking-wide text-slate-500">
          Mazo completado
        </p>
        <p className="font-display text-4xl font-bold text-slate-50">
          {known} / {total}
        </p>
        <p className="text-sm text-slate-400">tarjetas que ya sabías.</p>
        <button
          type="button"
          onClick={restart}
          className="mt-2 rounded-lg bg-accent/20 px-5 py-2.5 text-sm font-medium text-accent transition-colors hover:bg-accent/30"
        >
          Repasar de nuevo
        </button>
      </div>
    );
  }

  return (
    <div className="mx-auto flex max-w-2xl flex-col gap-5 px-6 py-6">
      <div className="flex items-center justify-between text-xs font-medium text-slate-500">
        <span>
          Tarjeta {index + 1} / {total}
        </span>
        <span>Sabidas: {known}</span>
      </div>

      {/* Card */}
      <button
        type="button"
        onClick={() => setFlipped((f) => !f)}
        className="flex min-h-[16rem] w-full flex-col justify-center rounded-2xl border border-slate-800 bg-slate-900/40 px-6 py-8 text-left transition-colors hover:border-slate-700"
      >
        {!flipped ? (
          <div className="flex flex-col items-center gap-2 text-center">
            <span className="font-display text-2xl font-bold text-slate-50">
              {card.front}
            </span>
            {card.sub && (
              <span className="text-sm italic text-slate-500">{card.sub}</span>
            )}
            <span className="mt-4 text-xs uppercase tracking-wide text-slate-600">
              Toca para revelar
            </span>
          </div>
        ) : (
          <dl className="flex flex-col gap-3">
            {card.facts.map((f) => (
              <div key={f.label}>
                <dt className="text-xs font-semibold uppercase tracking-wide text-accent/80">
                  {f.label}
                </dt>
                <dd className="text-sm leading-relaxed text-slate-200">
                  {f.value}
                </dd>
              </div>
            ))}
          </dl>
        )}
      </button>

      {/* Grade controls — only after the card is flipped. */}
      {flipped ? (
        <div className="flex gap-3">
          <button
            type="button"
            onClick={() => grade(false)}
            className="flex-1 rounded-lg border border-slate-700 px-4 py-2.5 text-sm font-medium text-slate-300 transition-colors hover:bg-slate-800/60"
          >
            Repasar
          </button>
          <button
            type="button"
            onClick={() => grade(true)}
            className="flex-1 rounded-lg bg-emerald-600/20 px-4 py-2.5 text-sm font-medium text-emerald-300 transition-colors hover:bg-emerald-600/30"
          >
            La sabía
          </button>
        </div>
      ) : (
        <p className="text-center text-xs text-slate-600">
          Intenta recordar el origen, la inserción y la inervación antes de girar.
        </p>
      )}
    </div>
  );
}
