// src/components/study/QuizView.tsx
//
// A self-contained quiz session over a region's muscles. Questions are
// generated by studyEngine.buildQuizQuestions() from the existing clinical
// data, sampled to SESSION_SIZE, and presented one at a time with immediate
// feedback. The best score is persisted via studyProgress so the student can
// track improvement (and, later, sync it to their account).

import { useMemo, useState } from 'react';
import type { Muscle } from '../../types/muscle';
import { buildQuizQuestions, shuffle, type QuizQuestion } from '../../lib/studyEngine';
import { recordQuiz } from '../../lib/studyProgress';

const SESSION_SIZE = 10;

interface QuizViewProps {
  region: string;
  muscles: Muscle[];
  /** Called after a session is recorded, so the parent can refresh its stats. */
  onFinished?: () => void;
}

export function QuizView({ region, muscles, onFinished }: QuizViewProps) {
  // Build a fresh session whenever the user (re)starts. `seed` forces a new
  // sample + reshuffle without recomputing the whole pool's identity.
  const [seed, setSeed] = useState(0);
  const session = useMemo<QuizQuestion[]>(() => {
    const pool = buildQuizQuestions(muscles);
    return shuffle(pool).slice(0, SESSION_SIZE);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [muscles, seed]);

  const [index, setIndex] = useState(0);
  const [picked, setPicked] = useState<string | null>(null);
  const [score, setScore] = useState(0);
  const [done, setDone] = useState(false);

  if (session.length === 0) {
    return (
      <EmptyState text="No hay preguntas suficientes para esta región todavía." />
    );
  }

  const q = session[index];
  const total = session.length;
  const answered = picked != null;
  const pickedCorrect = answered && q.options.find((o) => o.id === picked)?.correct;

  function choose(optionId: string) {
    if (answered) return;
    setPicked(optionId);
    if (q.options.find((o) => o.id === optionId)?.correct) {
      setScore((s) => s + 1);
    }
  }

  function next() {
    if (index + 1 < total) {
      setIndex((i) => i + 1);
      setPicked(null);
    } else {
      const pct = (score / total) * 100;
      recordQuiz(region, pct);
      setDone(true);
      onFinished?.();
    }
  }

  function restart() {
    setIndex(0);
    setPicked(null);
    setScore(0);
    setDone(false);
    setSeed((s) => s + 1);
  }

  if (done) {
    const pct = Math.round((score / total) * 100);
    return (
      <div className="mx-auto flex max-w-lg flex-col items-center gap-4 px-6 py-10 text-center">
        <p className="font-display text-sm font-semibold uppercase tracking-wide text-slate-500">
          Resultado
        </p>
        <p className="font-display text-5xl font-bold text-slate-50">{pct}%</p>
        <p className="text-sm text-slate-400">
          {score} de {total} correctas.
        </p>
        <button
          type="button"
          onClick={restart}
          className="mt-2 rounded-lg bg-accent/20 px-5 py-2.5 text-sm font-medium text-accent transition-colors hover:bg-accent/30"
        >
          Repetir cuestionario
        </button>
      </div>
    );
  }

  return (
    <div className="mx-auto flex max-w-2xl flex-col gap-5 px-6 py-6">
      {/* Progress + score */}
      <div className="flex items-center justify-between text-xs font-medium text-slate-500">
        <span>
          Pregunta {index + 1} / {total}
        </span>
        <span>Aciertos: {score}</span>
      </div>
      <div className="h-1 w-full overflow-hidden rounded-full bg-slate-800">
        <div
          className="h-full rounded-full bg-accent transition-all"
          style={{ width: `${((index + (answered ? 1 : 0)) / total) * 100}%` }}
        />
      </div>

      {/* Prompt */}
      <h2 className="font-display text-lg font-semibold leading-snug text-slate-100">
        {q.prompt}
      </h2>

      {/* Options */}
      <div className="flex flex-col gap-2">
        {q.options.map((o) => {
          const isPicked = picked === o.id;
          const reveal = answered && o.correct;
          const wrongPick = answered && isPicked && !o.correct;
          return (
            <button
              key={o.id}
              type="button"
              disabled={answered}
              onClick={() => choose(o.id)}
              className={[
                'rounded-xl border px-4 py-3 text-left text-sm transition-colors',
                reveal
                  ? 'border-emerald-600/60 bg-emerald-950/40 text-emerald-200'
                  : wrongPick
                    ? 'border-rose-700/60 bg-rose-950/40 text-rose-200'
                    : answered
                      ? 'border-slate-800 text-slate-500'
                      : 'border-slate-800 text-slate-200 hover:border-slate-600 hover:bg-slate-800/40',
              ].join(' ')}
            >
              {o.text}
            </button>
          );
        })}
      </div>

      {/* Feedback + next */}
      {answered && (
        <div className="flex items-center justify-between gap-3 border-t border-slate-800/60 pt-4">
          <p
            className={`text-sm font-medium ${
              pickedCorrect ? 'text-emerald-400' : 'text-rose-400'
            }`}
          >
            {pickedCorrect ? '¡Correcto!' : 'Respuesta incorrecta'}
          </p>
          <button
            type="button"
            onClick={next}
            className="rounded-lg bg-accent/20 px-5 py-2 text-sm font-medium text-accent transition-colors hover:bg-accent/30"
          >
            {index + 1 < total ? 'Siguiente' : 'Ver resultado'}
          </button>
        </div>
      )}
    </div>
  );
}

function EmptyState({ text }: { text: string }) {
  return (
    <div className="flex h-full items-center justify-center px-6 py-10">
      <p className="max-w-sm text-center text-sm text-slate-500">{text}</p>
    </div>
  );
}
