// GENERATED by scripts/build-premium-content.mts — do not edit by hand.
//
// Static imports on purpose: Supabase bundles what a function imports, so a
// dynamic path would deploy an empty folder and every request would 500.

import ankle from './payloads/ankle.json' with { type: 'json' };
import cervical from './payloads/cervical.json' with { type: 'json' };
import elbow from './payloads/elbow.json' with { type: 'json' };
import hip from './payloads/hip.json' with { type: 'json' };
import knee from './payloads/knee.json' with { type: 'json' };
import lumbar from './payloads/lumbar.json' with { type: 'json' };
import thoracic from './payloads/thoracic.json' with { type: 'json' };

export const PAYLOADS: Record<string, unknown> = {
  ankle,
  cervical,
  elbow,
  hip,
  knee,
  lumbar,
  thoracic,
};
