// scripts/build-premium-content.mts
//
// Serialises the PREMIUM regions' clinical library into the JSON payloads that
// the `content` edge function serves after checking the caller's subscription.
//
// WHY: the paid library used to be compiled into public JavaScript chunks, so
// anyone could fetch them without signing up. Splitting the bundle fixed the
// download size, not the leak. Now the free tier stays bundled and every paid
// region lives behind an entitlement check.
//
// Run:  npm run build-premium-content
// Out:  supabase/functions/content/payloads/<region>.json  (+ payloads.ts index)
//
// RE-RUN THIS WHENEVER YOU EDIT PREMIUM CLINICAL DATA, then redeploy the
// function. `premium-content.test.ts` fails if a payload is missing or stale,
// so a forgotten run is caught by `npm test` rather than by a user.

import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FREE_REGIONS } from '../src/auth/entitlements.ts';
import {
  ALL_CASES_BY_REGION,
  ALL_MUSCLE_CONTENT_BY_REGION,
  ALL_MUSCLES_BY_REGION,
  ALL_REGION_IDS,
  ALL_ROM_BY_REGION,
  ALL_ROM_LOOKUP_BY_REGION,
  ALL_PATHOLOGIES_BY_REGION,
  ALL_TESTS_BY_REGION,
  ALL_TRACK_BY_REGION,
} from '../src/data/fullContent.ts';
import type { PremiumRegionPayload } from '../src/data/premiumStore.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(HERE, '../supabase/functions/content/payloads');

/** Regions whose content must be paid for. Derived, never hand-listed. */
export const PREMIUM_REGION_IDS: string[] = ALL_REGION_IDS.filter(
  (r) => !FREE_REGIONS.has(r),
).sort();

/** Build one region's payload exactly as the client store expects it. */
export function buildPayload(region: string): PremiumRegionPayload {
  return {
    region,
    muscles: ALL_MUSCLES_BY_REGION[region] ?? [],
    // Resolved at BUILD time: for the spine this is the whole-spine union, so
    // the runtime never needs a sibling region loaded to render this one.
    romLookupMuscles: ALL_ROM_LOOKUP_BY_REGION[region] ?? ALL_MUSCLES_BY_REGION[region] ?? [],
    content: ALL_MUSCLE_CONTENT_BY_REGION[region] ?? {},
    rom: ALL_ROM_BY_REGION[region] ?? [],
    track: ALL_TRACK_BY_REGION[region] ?? null,
    tests: ALL_TESTS_BY_REGION[region] ?? [],
    cases: ALL_CASES_BY_REGION[region] ?? [],
    pathologies: ALL_PATHOLOGIES_BY_REGION[region] ?? [],
  };
}

function main(): void {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  let total = 0;
  for (const region of PREMIUM_REGION_IDS) {
    const json = JSON.stringify(buildPayload(region));
    writeFileSync(resolve(OUT_DIR, `${region}.json`), json, 'utf8');
    total += json.length;
    console.log(
      `  ${region.padEnd(10)} ${(json.length / 1024).toFixed(0).padStart(4)} KB`,
    );
  }

  // A generated index so the Deno function imports the payloads statically:
  // edge deployments bundle what is imported, and a dynamic path would not be
  // included.
  const index = [
    '// GENERATED by scripts/build-premium-content.mts — do not edit by hand.',
    '//',
    "// Static imports on purpose: Supabase bundles what a function imports, so a",
    '// dynamic path would deploy an empty folder and every request would 500.',
    '',
    ...PREMIUM_REGION_IDS.map(
      (r) => `import ${r} from './payloads/${r}.json' with { type: 'json' };`,
    ),
    '',
    'export const PAYLOADS: Record<string, unknown> = {',
    ...PREMIUM_REGION_IDS.map((r) => `  ${r},`),
    '};',
    '',
  ].join('\n');
  writeFileSync(resolve(dirname(OUT_DIR), 'payloads.ts'), index, 'utf8');

  console.log(
    `\n${PREMIUM_REGION_IDS.length} regiones premium · ${(total / 1024).toFixed(0)} KB en total`,
  );
  console.log(`Escrito en ${OUT_DIR}`);
  console.log('\nRecuerda desplegar:  supabase functions deploy content');
}

// Only run when invoked as a script; the test imports the helpers above.
const invokedDirectly =
  process.argv[1] != null && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) main();

/** Read back what is currently on disk (used by the freshness test). */
export function readWrittenPayload(region: string): PremiumRegionPayload | null {
  try {
    if (!readdirSync(OUT_DIR).includes(`${region}.json`)) return null;
    return JSON.parse(
      readFileSync(resolve(OUT_DIR, `${region}.json`), 'utf8'),
    ) as PremiumRegionPayload;
  } catch {
    return null;
  }
}
